<html>
    <head>
        <title></title>
        
        <link rel="stylesheet" type="text/css" href="css/estilo.css">
        
    </head>
    
    <body>
        
        <div id="contenedor-juego">
            
            <div id="contenedor-marcianitos"></div>
            
            <div id="tanque"><img width="50px" src="img/player.png"></div>
            
            <div id="bala0" class="bala">|</div>
            <div id="bala1" class="bala">|</div>
            <div id="bala2" class="bala">|</div>
            <div id="bala3" class="bala">|</div>
            <div id="bala4" class="bala">|</div>
            <div id="bala5" class="bala">|</div>
            <div id="bala6" class="bala">|</div>
            <div id="bala7" class="bala">|</div>
            <div id="bala8" class="bala">|</div>
            <div id="bala9" class="bala">|</div>
            
            <a href="#" onclick="izquierda();">Izquierda.</a>
            <a href="#" onclick="disparar();">Disparar.</a>
            <a href="#" onclick="derecha();">Derecha.</a>
            <a href="#" onclick="arriba();">Arriba.</a>

            
        </div>        
        
        <script src="js/variables_carga.js"></script>
        <script src="js/cargue.js"></script>
        <script src="js/jugar_carga.js"></script>
        <script src="js/movimiento.js"></script>
        <script src="js/maquina.js"></script>
        <script src="js/colisiones.js"></script>

        <form method="get" action="controlador/control.php">

            <span class="puntaje_txt">Puntaje</span><input type="text" name="puntaje" id="tabla_puntaje">
            <input type="submit" value="enviar" name="enviar" id="boton">

        </form>
        
    </body>

    <?php

        require_once($contenido);

    ?>

</html>